version: 0.2

phases:
  install:
    commands:
      - echo Moving into backend folder
      - cd prepmentor-ai/backend
      - chmod +x gradlew

  build:
    commands:
      - echo Building backend app...
      - ./gradlew build

artifacts:
  files:
    - prepmentor-ai/backend/build/libs/*.jar
