version: 0.2

phases:
  install:
    commands:
      - echo Moving into backend folder
      - cd backend
      - echo Installing dependencies...
      - chmod +x gradlew
      - ./gradlew clean

  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build -x test

artifacts:
  files:
    - backend/build/libs/*.jar
